name: listapp
description: A to-do list app.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mysql_client: ^0.0.27
  http: ^1.2.0
  
  flutter:
    sdk: flutter
  provider: ^6.0.0  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter: 
  uses-material-design: true

